seongdongps/urls.py
from django.contrib import admin    
from django.urls import path, include

from seongdongps import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main_page, name="main_page"),
    #path('main/',Sub.as_view()),
    path('survey/', include('survey.urls')),
    
]

survey/urls.py
from django.urls import path

from .views import views

app_name = 'survey'

urlpatterns = [
    path('survey_info/', views.survey_info, name='survey_info'),
    path('survey/', views.survey, name='survey'),
    path('survey_end/', views.survey_end, name='survey_end'),
]

survey/models.py
from django.db import models

# Create your models here.

class Survey(models.Model):
    q1 = models.CharField(max_length=50)
    q2 = models.CharField(max_length=50)
    q3 = models.CharField(max_length=50)
    q4 = models.CharField(max_length=50)
    q5_1 = models.CharField(max_length=50)
    q5_2 = models.CharField(max_length=50)
    q6 = models.CharField(max_length=200)
    q7 = models.CharField(max_length=50)
    q8 = models.CharField(max_length=50)
    q9 = models.CharField(max_length=50)
    q10 = models.CharField(max_length=50)
    
    # https://redk.tistory.com/39 메타 설명사이트
    class Meta:
        db_table = 'survey_result'
        verbose_name = '설문결과'
        verbose_name_plural = '설문결과'
        

seongdongps/views.py
from django.shortcuts import render
from rest_framework.views import APIView


# class Sub(APIView):
#     def get(self, request):
#         print("get으로 호출")
#         return render(request, "index.html")

#     def post(self, request):
#         print("post로 호출")
#         return render(request, "index.html")
    
def main_page(request):
    return render(request, 'index.html')

survey/views/views.py
import json

from django.http import JsonResponse
from django.shortcuts import render
from survey.models import Survey
# Create your views here.


def survey_info(request):

    return render(request, 'survey/survey_info.html')


def survey(request):
    if request.method == 'POST':

        jsonObject = json.loads(request.body)
        q1asr = jsonObject['q1asr']
        q2asr = jsonObject['q2asr']
        q3asr = jsonObject['q3asr']
        q4asr = jsonObject['q4asr']
        q5asr_1 = jsonObject['q5asr_1']
        q5asr_2 = jsonObject['q5asr_2']
        q6asr = jsonObject['q6asr']
        q7asr = jsonObject['q7asr']
        q8asr = jsonObject['q8asr']
        q9asr = jsonObject['q9asr']
        q10asr = jsonObject['q10asr']
        survey = Survey(
            q1=q1asr,
            q2=q2asr,
            q3=q3asr,
            q4=q4asr,
            q5_1=q5asr_1,
            q5_2=q5asr_2,
            q6=q6asr,
            q7=q7asr,
            q8=q8asr,
            q9=q9asr,
            q10=q10asr
        )
        survey.save()
        context = {
            'proc' : 'success'
        }

        return JsonResponse(context, safe=False)

    return render(request, 'survey/survey.html')


def survey_end(request):

    return render(request, 'survey/survey_end.html')

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>서울성동경찰서</title>
    <link rel="stylesheet" href="{% static '/css/style.css'%}">
    <script src="{% static '/js/jquery-3.2.1.min.js'%}"></script>
    <script src="{% static '/js/common.js'%}"></script>
</head>
<body>
    <div id="wrap">
    {% block content %}

    {% endblock %}
    </div>
</body>
</html>

templates/index.html
{% load static %}
<picture>
    <source srcset="{% static '/images/s-img3-m.png'%}" media="(max-width:1000px)" >
    <img src="{% static '/images/s-img3.png'%}" alt="지역공동체 치안활성화 주민설문조사" >
</picture>

templates/survey/survey_end.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="sub">
            <div class="subSectionEnd">
                <h1 class="logoArea"><span class="logo">서울성동경찰서</span></h1>
                <div class="subSection03">
                    <picture>
                        <source srcset="{% static '/images/s-img3-m.png'%}" media="(max-width:1000px)" >
                        <img src="{% static '/images/s-img3.png'%}" alt="지역공동체 치안활성화 주민설문조사" >
                    </picture>
                </div>
            </div>
            <div class="btmBtn">
                <a href="/" class="btnTy1">완료</a>
            </div>
        </div>

{% endblock %}

templates/survey/survey_info.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="sub">
    <div class="subSection">
        <h1 class="logoArea"><span class="logo">양주시로고</span></h1>
        <div class="subSection01">
            <h2 class="subTitle1">
                <picture>
                    <source srcset="{% static '/images/s-title-m.png'%}" media="(max-width:1000px)" >
                    <img src="{% static '/images/s-title.png'%}" alt="지역공동체 치안활성화 주민설문조사" >
                </picture>
            </h2>
            <div class="subSectCont01">
                <p class="tx3">안녕하십니까? </p>
                <p class="tx1">성동경찰서는 성동구청과 협업하여 범죄 예방 인프라
                    구축(CCTV ㆍ가로등 설치 등)으로 범죄 예방 및 주민들의
                    불안감을 해소토록 노력하고 있으며, 이에 설문조사를
                    통해 주민들의 의견을 청취, 現 설치된 범죄 예방 인프라
                    시설을 확인하고 향후 범죄 예방 사업에 반영하고자 합니다.</p>
                <p class="tx1">설문지에 응답하신 내용은 연구 목적 이외에는 절대
                    사용되지 않으며, 통계법 제33조(비밀의 보호) 및 제34조
                    (통계 종사자 등의 의무)에 의거 비밀이 보호되오니
                    바쁘시더라도 조금만 협조해 주시면 감사하겠습니다.</p>
                <p class="tx1">평소 선생님께서 느낀 바를 솔직하게 응답하여 주신다면
                    지역사회의 범죄 예방을 위한 정책을 마련하는 데 귀중한
                    자료로 활용될 것입니다.
                    바쁘신 중에 시간을 내어 설문에 협조하여 주신 데 대하여
                    깊이 감사드립니다.</p>
                <p class="tx2">성동경찰서 생활안전과</p>
            </div>
        </div>
    </div>
    <div class="btmBtn">
        <a href="{% url 'survey:survey' %}" class="btnTy1">다음</a>
    </div>
</div>
{% endblock %}